C:37:"PHPUnit\Runner\DefaultTestResultCache":990:{a:2:{s:7:"defects";a:5:{s:7:"Warning";i:6;s:51:"Test\Unit\RouterTest::does_our_register_method_work";i:3;s:46:"Test\Unit\RouterTest::it_registers_a_get_route";i:3;s:61:"Test\Unit\RouterTest::there_is_no_route_when_route_is_created";i:4;s:74:"Test\Unit\RouterTest::it_throws_route_not_found_exception with data set #3";i:3;}s:5:"times";a:9:{s:7:"Warning";d:0.015;s:51:"Test\Unit\RouterTest::does_our_register_method_work";d:0.015;s:56:"Test\Unit\RouterTest::test_does_our_register_method_work";d:0.016;s:46:"Test\Unit\RouterTest::it_registers_a_get_route";d:0.008;s:61:"Test\Unit\RouterTest::there_is_no_route_when_route_is_created";d:0.009;s:74:"Test\Unit\RouterTest::it_throws_route_not_found_exception with data set #0";d:0.009;s:74:"Test\Unit\RouterTest::it_throws_route_not_found_exception with data set #1";d:0;s:74:"Test\Unit\RouterTest::it_throws_route_not_found_exception with data set #2";d:0;s:74:"Test\Unit\RouterTest::it_throws_route_not_found_exception with data set #3";d:0;}}}